version: '3'

services:
  # PHP Application
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

  # MySQL Database
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:6000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
